#download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "./household_power_consumption.zip")
#unzip("./household_power_consumption.zip")
hpc <- read.table("household_power_consumption.txt", header =  TRUE, sep = ";", na.strings = "?")
hpc$DateTime <- paste(hpc$Date, hpc$Time, sep = " ")
hpc$DateTime <- strptime(hpc$DateTime, format = "%d/%m/%Y %H:%M:%S", tz = "")
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc <- subset(hpc, hpc$Date >= "2007-02-01" & hpc$Date <= "2007-02-02")
hpc$Time <- strptime(hpc$Time, format = "%H:%M:%S", tz = "")
hpc <- transform(hpc, DateTime = as.POSIXct(paste(hpc$Date, hpc$Time), format="%Y-%m-%d %H:%M:%S"))
hpc <- transform(hpc, Day = weekdays(hpc$Date))
#png(file="Plot1.png",width=480,height=480)
hist(hpc$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.copy(png,"Plot1.png",width=480,height=480)
dev.off
