#download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "./household_power_consumption.zip")
#unzip("./household_power_consumption.zip")
hpc <- read.table("household_power_consumption.txt", header =  TRUE, sep = ";", na.strings = "?")
hpc$DateTime <- paste(hpc$Date, hpc$Time, sep = " ")
hpc$DateTime <- strptime(hpc$DateTime, format = "%d/%m/%Y %H:%M:%S", tz = "")
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc <- subset(hpc, hpc$Date >= "2007-02-01" & hpc$Date <= "2007-02-02")
hpc$Time <- strptime(hpc$Time, format = "%H:%M:%S", tz = "")
hpc <- transform(hpc, Day = weekdays(hpc$Date))
plot(hpc$DateTime, hpc$Global_active_power, type = "n", ylim=range(0:40), xlab = "", ylab = "Energy sub metering")
lines(hpc$DateTime, hpc$Sub_metering_1, type = "l",  col = "black")
lines(hpc$DateTime, hpc$Sub_metering_2, type = "l",  col = "red")
lines(hpc$DateTime, hpc$Sub_metering_3, type = "l",  col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty=c(1,1,1), cex=0.5, pt.cex = 3)
dev.copy(png,"Plot3.png", width=480,height=480)
dev.off()
